#!/bin/bash
#Get package manager
# Debian, Ubuntu and derivatives (with apt-get)
if [[ ! -e $HOME/$DIR/config/pkgmngr ]]; then
	echo "###################"
	echo "First time setup..."
	echo "###################"
	echo "Run 'alias' to view the aliases loaded at any time."
	#TODO Check that it is okay to continue
	# mkdir $DIR &> /dev/null
	if command -v apt-get &> /dev/null; then
       		echo "PKGMNGR='apt-get'" > $HOME/$DIR/config/pkgmngr 	
		#apt-get install $PKGSTOINSTALL
        # OpenSuse (with zypper)
	elif command -v zypper &> /dev/null; then
		echo "PKGMNGR='zypper'" > $HOME/$DIR/config/pkgmngr
		#"zypper in $PKGSTOINSTALL"
        # Mandriva (with urpmi)
	elif command -v urpmi &> /dev/null; then
      		echo "PKGMNGR='urmpi'" > $HOME/$DIR/config/pkgmngr
		#urpmi $PKGSTOINSTALL
        # Fedora and CentOS (with yum)
	elif command -v yum &> /dev/null; then
      		echo "PKGMNGR='yum'" > $HOME/$DIR/config/pkgmngr
		#yum install $PKGSTOINSTALL
        # ArchLinux (with pacman)
	elif command -v pacman &> /dev/null; then
       		echo "PKGMNGR='pacman'" > $HOME/$DIR/config/pkgmngr
		#pacman -Sy $PKGSTOINSTALL
        # Else, if no package manager has been found
	else
        # Set $NOPKGMANAGER
		echo "PKGMNGR=''" > $HOME/$DIR/config/pkgmngr
		. $HOME/$DIR/config/pkgmngr
		if [[ $PKGMNGR == '' ]]; then
			echo "ERROR 1: No package manager found. Please, manually add these settings into $HOME/$DIR/config/pkgmngr"
		fi
fi
	echo -e "\e[0;31m In order for the package manager aliases to work properly you may also have to make this script root's .bashrc \e[0m"
	#TODO Automatically 
else
	. $HOME/$DIR/config/pkgmngr
fi

if [[ $PKGMNGR = 'apt-get' ]]; then
	INSTALLCMD="sudo $PKGMNGR install"
	UPDATECMD="sudo $PKGMNGR update && sudo $PKGMNGR dist-upgrade && sudo $PKGMNGR clean"
	UPDATEMIRRORCMD="sudo $PKGMNGR update"
	REMOVECMD="sudo $PKGMNGR remove"
elif [[ $PKGMNGR = 'zypper' ]]; then
	INSTALLCMD='$PKGMNGR in'
	UPDATECMD='$PKGMNGR up'
	UPDATEMIRRORCMD='$PKGMNGR ref'
	REMOVECMD='$PKGMNGR remove'
elif [[ $PKGMNGR = 'urmpi' ]]; then
	INSTALLCMD='$PKGMNGR' 
        UPDATECMD='$PKGMNGR.update -a'
        UPDATEMIRRORCMD='$UPDATECMD && echo "Cannot just update mirrors with urmpi"'
        REMOVECMD='urpme'
elif [[ $PKGMNGR = 'yum'  ]]; then
	INSTALLCMD='$PKGMNGR install'
        UPDATECMD='$PKGMNGR update'
        UPDATEMIRRORCMD='$PKGMNGR update && echo "Cannot just update mirrors with yum"'
        REMOVECMD='$PKGMNGR remove'
elif [[ $PKGMNGR = 'pacman' || $PKGMNGR = 'pacaur' || $PKGMNGR = 'yaourt' ]]; then
	INSTALLCMD='sudo $PKGMNGR -Sy' 
        UPDATECMD='sudo $PKGMNGR -Syu'
        UPDATEMIRRORCMD='sudo $PKGMNGR -Syy'
        REMOVECMD='sudo $PKGMNGR -Rs'
else
	if [[ ! -e $HOME/$DIR/config/pkgmngr ]]; then
		echo "ERROR 2: No package manager found. Please, manually add these settings into $HOME/$DIR/config/pkgmngr"
	fi
fi

