#!/bin/bash
#Get package manager
if [[ ! -e $HOME/$DIR/config/pkgmngr ]]; then
	echo "###################"
	echo "First time setup..."
	echo "###################"
	echo "Run 'alias' to view the aliases loaded at any time."
	#TODO Check that it is okay to continue
  #TODO Add alpine apk package manager
	# mkdir $DIR &> /dev/null
        # Debian, Ubuntu and derivatives (with apt-get)
    if command -v apt-get &> /dev/null; then
       		echo "PKGMNGR='apt-get'" > $HOME/$DIR/config/pkgmngr
		    #apt-get install $PKGSTOINSTALL
        # OpenSuse (with zypper)
	elif command -v zypper &> /dev/null; then
		echo "PKGMNGR='zypper'" > $HOME/$DIR/config/pkgmngr
		    #"zypper in $PKGSTOINSTALL"
        # Mandriva (with urpmi)
	elif command -v urpmi &> /dev/null; then
      		echo "PKGMNGR='urmpi'" > $HOME/$DIR/config/pkgmngr
		    #urpmi $PKGSTOINSTALL
        # Fedora and CentOS (with yum)
	elif command -v yum &> /dev/null; then
      		echo "PKGMNGR='yum'" > $HOME/$DIR/config/pkgmngr
		    #yum install $PKGSTOINSTALL
        # ArchLinux (with pacman)
	elif command -v pacman &> /dev/null; then
            if command -v pacaur &> /dev/null; then
                    echo "PKGMNGR='pacaur'" > $HOME/$DIR/config/pkgmngr
            elif command -v yaourt &> /dev/null; then
                    echo "PKGMNGR='yaourt'" > $HOME/$DIR/config/pkgmngr
            else
                    echo "PKGMNGR='pacman'" > $HOME/$DIR/config/pkgmngr
            fi
            #pacman -Sy $PKGSTOINSTALL
        # Else, if no package manager has been found
	else
        # Set $NOPKGMANAGER
		echo "PKGMNGR=''" > $HOME/$DIR/config/pkgmngr
		. $HOME/$DIR/config/pkgmngr
		if [[ $PKGMNGR == '' ]]; then
			echo "ERROR 1: No package manager found. Please, manually add these settings into $HOME/$DIR/config/pkgmngr"
		fi
fi
	echo -e "\e[0;31mIn order for the package manager aliases to work properly you may also have to make this script root's .bashrc \e[0m"
	#TODO Automatically
else
	. $HOME/$DIR/config/pkgmngr
fi

if [[ $PKGMNGR = 'apt-get' ]]; then
	INSTALLCMD="sudo $PKGMNGR install"
	UPDATECMD="sudo $PKGMNGR update && sudo $PKGMNGR dist-upgrade && sudo $PKGMNGR clean"
	UPDATEMIRRORCMD="sudo $PKGMNGR update"
	REMOVECMD="sudo $PKGMNGR remove"
elif [[ $PKGMNGR = 'zypper' ]]; then
	INSTALLCMD='sudo $PKGMNGR in'
	UPDATECMD='sudo $PKGMNGR up'
	UPDATEMIRRORCMD='sudo $PKGMNGR ref'
	REMOVECMD='sudo $PKGMNGR remove'
elif [[ $PKGMNGR = 'urmpi' ]]; then
	INSTALLCMD='sudo $PKGMNGR'
  UPDATECMD='sudo $PKGMNGR.update -a'
  UPDATEMIRRORCMD='sudo $UPDATECMD && echo "Cannot just update mirrors with urmpi"'
  REMOVECMD='sudo urpme'
elif [[ $PKGMNGR = 'yum'  ]]; then
	INSTALLCMD='sudo $PKGMNGR install'
  UPDATECMD='sudo $PKGMNGR update'
  UPDATEMIRRORCMD='sudo $PKGMNGR update && echo "Cannot just update mirrors with yum"'
  REMOVECMD='sudo $PKGMNGR remove'
elif [[ $PKGMNGR = 'pacman' || $PKGMNGR = 'pacaur' || $PKGMNGR = 'yaourt' ]]; then
	INSTALLCMD='sudo $PKGMNGR -Sy'
  UPDATECMD='sudo $PKGMNGR -Syu'
  UPDATEMIRRORCMD='sudo $PKGMNGR -Syy'
  REMOVECMD='sudo $PKGMNGR -Rs'
else
	if [[ ! -e $HOME/$DIR/config/pkgmngr ]]; then
		echo "ERROR 2: No package manager found. Please, manually add these settings into $HOME/$DIR/config/pkgmngr"
	fi
fi

#System / Package manager commands
alias inst="$INSTALLCMD"
alias update="$UPDATEMIRRORCMD"
alias upgrade="$UPDATECMD"
alias remove="$REMOVECMD"
