#!/bin/bash
if [[ -z "$PS1_GIT" ]]; then	
	PS1="$PS1_GIT"
else
	if [[ -e /usr/share/git/completion/git-prompt.sh ]]; then
		. /usr/share/git/completion/git-prompt.sh
		PS1="$(__git_ps1) -> "	
	fi
fi	
