#!/bin/bash
PS1="\[\e[42;30m\][\w]\[\e[0m\]\[\e[42;30m\] $(git branch | grep '*' | cut -c3-)\[\e[33m\]$(if [[ $(git branch | grep '*' | cut -c3-) == 'master' ]]; then echo '☆ '; else echo '☢ '; fi)\e[0m\[\e[32m\]⮀\[\e[0m\] "
