#!/bin/bash
PS1="\[\e[42;30m\]\u\[\e[42;30m\]─[\w\[\e[0m\]\[\e[42;30m\]]ハッカー\[\e[0m\]\[\e[0;32m\]⮀\[\e[0m\] "
PS1_GIT="\[\e[42;30m\][\w]\[\e[0m\]\[\e[42;30m\] $(git branch 2> /dev/null | grep '*' | cut -c3-)\[\e[33m\]$(if [[ $(git branch 2> /dev/null | grep '*' | cut -c3-) == 'master' ]]; then echo '☆ '; else echo '☢ '; fi)\[\e[0m\]\[\e[32m\]⮀\[\e[0m\] "
