#!/bin/bash

###CONFIG SECTION###
DIR=".terrorshell"
THEME="prompt"
MODULES=(gitcheck gitcut banner pkgmngr terrorshell extract security)
###################

###TODO############
#* Add more package managers
#* Github update improvements
#* Alias's for designated directories
#* Improved / Cleaned up alias's
#* Inputrc bind in a seperate config file
#* Update command check for version info and warn that since it doesn't over-wright that they need to change files according to the VERSION file
###################

DATE="$(date +%m-%d)"

. $HOME/.terrorshell/themes/$THEME

for module in "${MODULES[@]}"
do
	. $HOME/$DIR/modules/$module
done


if [[ -e /etc/bash_completion ]]; then
	. /etc/bash_completion
fi

###Shopt Settings###
shopt -s autocd
shopt -s extglob
shopt -s checkwinsize

###Inputrc Settings###
bind 'set completion-ignore-case on'
bind 'set completion-prefix-display-length 2'
bind 'set show-all-if-ambiguous on'
bind 'set show-all-if-unmodified on'
bind 'set completion-map-case on'

#Aliases
#Battery / Monitor / Keyboard
alias bat='upower -d | grep percentage && upower -d | grep time'
alias battery='upower -d | grep percentage && upower -d | grep time'
alias bright='sudo setpci -s 00:02.0 F4.B=96'
alias kb='setxkbmap -option grp:alt_shift_toggle us,dvorak'

#Navigation
alias cl='clear'
alias ba='cd -'
alias disk='df -h'
alias up='cd ..'
alias rmf='rm -rfi'

#Safety features
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -I'
alias ln='ln -i'
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'
alias ls='ls --color=auto'
alias lsa='ls -a --color=auto'
alias lsl='ls -la --color=auto'
alias attach='tmux attach'
alias df='df -h'
alias du='du -c -h'
alias mkdir='mkdir -p -v'
alias md='mkdir -p'
alias rd='rmdir'
alias d='dirs -v'
alias openports='ss --all --numeric --processes --ipv4 --ipv6'

#etc
alias rfs='sshfs'
alias ip='curl -s http://checkip.dyndns.org/ | grep -o '[0-9][0-9]*.[0-9][0-9]*.[0-9][0-9]*.[0-9]*''
alias irc='irssi'
alias links='links google.com'
alias refresh='bash && kill -SIGKILL $$'
